runtime: python39  # Use Python 3.9 runtime, adjust as necessary

handlers:
  - url: /chatbot
    script: auto  # This will automatically detect the entrypoint

  # Handle static files (if any)
  - url: /static
    static_dir: static

entrypoint: gunicorn -b :$PORT main:app  # Use Gunicorn as the entrypoint
